server:
  port:8999

eureka:
  instance:
    hostname:localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/medicine/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
