server:
  port:8999

eureka:
  instance:
    hostname:localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/medicine/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**

        - id: procure-service
          uri: lb://procure-service
          predicates:
            - Path=/procure/**

        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/sale/**

